export const OVERVIEW_FIELD_DEFINITIONS = {
  device_name: { label: '设备名称', fallback: '--' },
  device_codename: { label: '设备代号', fallback: '--' },
  serial: { label: '序列号', fallback: '--' },
  state: { label: '设备状态', fallback: '--' },
  brand: { label: '品牌', fallback: '--' },
  android_version: { label: '安卓版本', fallback: '--' },
  os_version: { label: '系统版本', fallback: '--' },
  cpu_codename: { label: 'CPU 代号', fallback: '--' },
  cpu_arch: { label: 'CPU 架构', fallback: '--' },
  hardware_platform: { label: '硬件平台', fallback: '--' },
  board_id: { label: '主板 ID', fallback: '--' },
  resolution: { label: '分辨率', fallback: '--' },
  display_density: { label: '显示密度', fallback: '--' },
  unlock_state: { label: '解锁状态', fallback: '--' },
  ab_slot: { label: 'AB 分区', fallback: '--' },
  vndk_version: { label: 'VNDK 版本', fallback: '--' },
  uptime: { label: '开机时长', fallback: '--' },
  build_date: { label: '构建日期', fallback: '--' },
  build_version: { label: '编译版本', fallback: '--' },
  fingerprint: { label: '设备指纹', fallback: '--' },
  kernel_version: { label: '内核版本', fallback: '--' },
  manufacturer: { label: '制造商', fallback: '--' },
  product_model: { label: '产品型号', fallback: '--' },
  product_name: { label: '产品名称', fallback: '--' },
  security_patch: { label: '安全补丁', fallback: '--' },
  vendor_security_patch: { label: '厂商安全补丁', fallback: '--' },
  build_incremental: { label: '增量版本', fallback: '--' },
  build_type: { label: '构建类型', fallback: '--' },
  build_tags: { label: '构建标签', fallback: '--' },
  baseband_version: { label: '基带版本', fallback: '--' },
  soc_manufacturer: { label: 'SoC 厂商', fallback: '--' },
  soc_model: { label: 'SoC 型号', fallback: '--' },
  cpu_abilist: { label: 'CPU ABI 列表', fallback: '--' },
};

export const OVERVIEW_REPORT_FIELD_DEFINITIONS = {
  ...OVERVIEW_FIELD_DEFINITIONS,
  system_count: { label: '系统应用', fallback: '--' },
  user_count: { label: '用户应用', fallback: '--' },
  total_count: { label: '应用总数', fallback: '--' },
};

export const OVERVIEW_SUMMARY_FIELDS = [
  'device_name',
  'device_codename',
  'brand',
  'serial',
  'resolution',
  'unlock_state',
  'os_version',
  'build_version',
];

export const OVERVIEW_REPORT_FIELDS = [
  'state',
  'android_version',
  'manufacturer',
  'product_model',
  'product_name',
  'build_date',
  'security_patch',
  'vendor_security_patch',
  'build_incremental',
  'build_type',
  'build_tags',
  'fingerprint',
  'kernel_version',
  'vndk_version',
  'cpu_codename',
  'cpu_arch',
  'cpu_abilist',
  'soc_manufacturer',
  'soc_model',
  'hardware_platform',
  'board_id',
  'display_density',
  'ab_slot',
  'uptime',
  'baseband_version',
  'system_count',
  'user_count',
  'total_count',
];

export function createDefaultOverviewDeviceInfo() {
  return Object.fromEntries(
    Object.entries(OVERVIEW_FIELD_DEFINITIONS).map(([key, definition]) => [key, definition.fallback])
  );
}
