export const chargeModes = [
  { key: 'none', label: '模拟非充电', color: 'var(--color-text-muted)' },
  { key: 'wireless', label: '模拟无线充电', color: 'var(--status-recovery)' },
  { key: 'usb', label: '模拟 USB 充电', color: 'var(--color-info)' },
  { key: 'ac', label: '模拟直流充电', color: 'var(--color-success)' },
];

export const lockPresets = [
  { label: '15s', value: 15 },
  { label: '30s', value: 30 },
  { label: '60s', value: 60 },
  { label: '120s', value: 120 },
  { label: '5min', value: 300 },
  { label: '从不', value: 0 },
];

export const quickActions = [
  { label: '返回', icon: 'back', color: 'var(--color-info)', code: '4' },
  { label: '主页', icon: 'home', color: 'var(--color-success)', code: '3' },
  { label: '多任务', icon: 'recents', color: 'var(--status-recovery)', code: '187' },
  { label: '锁屏', icon: 'lock_screen', color: 'var(--color-danger)', code: '26' },
  { label: '截图', icon: 'screenshot', color: 'var(--color-info)', code: '120' },
];

export const statusIconItems = [
  { key: 'rotate', label: '自动旋转' },
  { key: 'data_saver', label: '流量节省' },
  { key: 'managed_profile', label: '工作资料' },
  { key: 'headset', label: '耳机' },
  { key: 'headphone', label: '耳机(头戴)' },
  { key: 'tty', label: 'TTY 模式' },
  { key: 'speakerphone', label: '免提' },
  { key: 'cast', label: '投屏' },
  { key: 'alarm', label: '闹铃' },
  { key: 'alarm_clock', label: '闹钟' },
  { key: 'performance_mode', label: '性能模式' },
  { key: 'location', label: '位置' },
  { key: 'gps', label: 'GPS' },
  { key: 'record', label: '录制' },
  { key: 'screen_record', label: '屏幕录制' },
  { key: 'camera', label: '相机' },
  { key: 'microphone', label: '麦克风' },
  { key: 'mute', label: '静音' },
  { key: 'volume', label: '音量' },
  { key: 'zen', label: '勿扰模式' },
  { key: 'bluetooth', label: '蓝牙' },
  { key: 'vpn', label: 'VPN' },
  { key: 'volte', label: 'VoLTE' },
  { key: 'vowifi', label: 'VoWiFi' },
  { key: 'network_speed', label: '网速' },
  { key: 'hd', label: '高清通话' },
  { key: 'mobile', label: '移动数据' },
  { key: 'disable_sim_1', label: '禁用 SIM1' },
  { key: 'disable_sim_2', label: '禁用 SIM2' },
  { key: 'wifi_deputy', label: 'WiFi 副卡' },
  { key: 'wifi', label: 'WiFi' },
  { key: 'airplane', label: '飞行模式' },
  { key: 'no_sim', label: '无 SIM 卡' },
  { key: 'satellite', label: '卫星' },
  { key: 'battery', label: '电池' },
  { key: 'hotspot', label: '热点' },
  { key: 'nfc', label: 'NFC' },
  { key: 'sync_active', label: '同步中' },
  { key: 'sync_failing', label: '同步失败' },
  { key: 'clock', label: '时钟' },
  { key: 'data_connection', label: '数据连接' },
  { key: 'ethernet', label: '以太网' },
  { key: 'phone_signal', label: '手机信号' },
  { key: 'ime', label: '输入法' },
  { key: 'secure', label: '安全' },
  { key: 'sensors_off', label: '传感器关闭' },
  { key: 'work', label: '工作模式' },
  { key: 'su', label: '超级用户' },
  { key: 'case', label: '保护壳' },
  { key: 'connected_display', label: '已连显示器' },
];
